[phases.setup]
nixPkgs = ["python311", "pip"]

# Sobrescribir la fase de instalaci√≥n de Node.js para que no se ejecute
[phases.setup.nodejs]
nixPkgs = []

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn api.index:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_NO_NODE = "1"
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_SKIP_NODE_DETECT = "1"

